# name: shared-workflow-red
# on:
#   workflow_dispatch:
#   push:
#     branches:
#       - "dev"
# job:
#   shared_dispatch_red:
#     uses: anup350/shared-blue/.github/workflows/blue.yaml@main
#     with:
#       print-colours: true
####
# name: Test and release
# on:
#   workflow_dispatch:
#   push:
#     paths-ignore:
#       - '**.md'
#     branches:
#       - "main"
# jobs:
#   shared:
#     uses: anup350/shared-blue/.github/workflows/blue.yaml@main
#     with:
#       enable-code-scans: true
#     secrets:
#       ghcr_token: ${{ secrets.ghcr_token }}